### ISSUE TITLE
open credentials.json: no such file or directory

### ISSUE THREAD

**Issue by gabrielmaialva33** [Juvenal-Yescas/gdown#1]
How to configure this credentials.json? If so, how?

`The file has exceeded the download limit, try download with your account
2020/09/23 21:56:39 Unable to read client secret file: open credentials.json: no such file or directory`

**Comment by juvenal-yescas** [comment]
@gabrielmaialva33  You can follow these steps:  [Go Quickstart](https://developers.google.com/drive/api/v3/quickstart/go)

**Comment by gabrielmaialva33** [comment]
> @gabrielmaialva33 You can follow these steps: [Go Quickstart](https://developers.google.com/drive/api/v3/quickstart/go)

Thank you very much!
